### ISSUE TITLE
How to install windows?

### ISSUE THREAD

**Issue by alvaro562003** [edrosten/TooN#13]
thanks

**Comment by alvaro562003** [comment]
same question on libcvd, TaG, GVars3.

**Comment by edrosten** [comment]
TooN should work fine on Windows. It is header only and doesn't require
compiling.

**Comment by edrosten** [comment]
Do you mean "compile on visual studio", or are you looking to compile them
under cygwin?

**Comment by alvaro562003** [comment]
sorry, i ignored that for toon. That's is ok for toon.

I try to install fivepoint from lui and drummond (https://bitbucket.org/whvlui/fivepoint).
The prerequisite is  libcvd, TaG, GVars3.

I am using microsoft visual studio 2015.

I close here and open an issue on libcvd. Thank you
