### ISSUE TITLE
How to install windows?

### ISSUE THREAD

**Issue by holazollil** [edrosten/TooN#8]
I use windows 8 - 64 bit machine. You said that "this code should work on unix or non-unix system". On unix, we should use ./configure;make; make install. But on windows, what can I use to install?

**Comment by edrosten** [comment]
On 31 July 2015 at 09:52, holazollil <notifications@github.com> wrote:

> I use windows 8 - 64 bit machine. You said that "this code should work on
> unix or non-unix system". On unix, we should use ./configure;make; make
> install. But on windows, what can I use to install?
>
TooN is a header only library, so all you need to do is point your include
path at the directory in which TooN resides.

On linux, "make" for TooN doesn't actually do anything, only the configure
and make install steps do. TooN will work out of the box without any
configuration.


-Ed

**Comment by holazollil** [comment]
Ok. Thanks your answer. TooN works now.

2015-07-31 14:38 GMT+03:00 Edward Rosten <notifications@github.com>:
